package server.engine;

/**
 * A change in the World State generated by the Game Engine.
 * It specifies all necessary information required to update the worldstate.
 * It also supports conversion to and from EventDatum for link transmission.
 */
public interface Event {

}
